### PR TITLE
scalajs-react 1.5.0; add scala 2.13 and drop 2.11

### PR DESCRIPTION
**Pull request by nafg**

### CODE REVIEW

**Comment by ramnivas** [comment]
@nafg When I tried to run 'sbt test', it failed with unresolved dependencies. Did that work fine for you?

**Comment by nafg** [comment]
That fixed it but now there's a new issue :(

**Comment by nafg** [comment]
@ramnivas can you see if clearing Travis' cache and restarting the build helps?

**Comment by ramnivas** [comment]
@nafg Does this work for you locally? When I tried it on my machine, I get:
```
[warn] 	:: org.scalatest#scalatest_sjs0.6_2.13;3.0.1: not found
[warn] 	:: org.scala-js#scalajs-dom_sjs0.6_2.13;0.9.6: not found
```
and then a subsequent failure due to this unresolved dependencies.

**Comment by nafg** [comment]
So maybe some more versions need to be bumped. But that's not what Travis is showing. Can you please clear travis's cache and restart the build

**Comment by ramnivas** [comment]
The code still doesn't compile with your changes. Can you locally try to compile/test? Basically, `sbt test` should succeed on your machine.

**Comment by nafg** [comment]
Did you clear Travis's cache?

**Comment by ramnivas** [comment]
No caches were set in Travis. Accessing its caching info gives the message: "No caches have been created yet".

I suggest that you try to "sbt test" locally and see if that works first. I can take a look at the Travis issue separately later.

**Comment by ramnivas** [comment]
LGTM. Thanks @nafg

**Pull request merged**
