### PR TITLE
scalajs-react 1.2.0

### PR DESCRIPTION
**Pull request by nafg**
Based on #30 by @jac3km4. All tests pass.

### CODE REVIEW

**Comment by ramnivas** [comment]
I still get the same error at in #30 
```
[info] Fast optimizing /Users/ramnivas/open-source/scalajs-react-bridge/core/target/scala-2.12/scalajs-react-bridge-test-fastopt.js
module.js:559
    throw err;
    ^

Error: Cannot find module 'jsdom'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at [stdin]:115:13
    at [stdin]:153:3
    at Script.runInThisContext (vm.js:65:33)
    at Object.runInThisContext (vm.js:197:38)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:662:30)
```

Are you able to run tests successfully? If so, any additional setup needed?

**Comment by nafg** [comment]
Hmm, I guess I must have not cleaned node_modules while working on it. I'll
have to tweak it a bit more. But there were much more serious errors that I
fixed.

More broadly, it's still using jsDependencies. Migrating to scalajs-bundler
would avoid these issues and make things simpler.

**Comment by nafg** [comment]
I think when you use JSDOMNodeJSEnv you're supposed to `npm install jsdom` maybe

**Comment by nafg** [comment]
Do you have travis set up?

**Comment by nafg** [comment]
`npm install jsdom` makes it work.

**Comment by ramnivas** [comment]
That worked. Thanks.

**Pull request merged**
